Safety/Controllers/OutPutController.cs
using Safety.Core;
using Safety.VM.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Safety.Controllers
{
    [Authorize(Roles = "Admin,User")]

    public class OutPutController : Controller
    {
        // GET: OutPut
        public ActionResult Index1()
        {

            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllInPut".ExecuParamsSqlOrStored(false, "TransActionCase".KVP(2)).AsList<InPutVM>();
            return View(model);

        }


        [HttpPost]
        public ActionResult GetAccount(int id = 0)
        {

            var Accounts = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Accounts.AddRange("Sp_AccountDrop".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<AccountDrop>().Select(s => new SelectListItem
            {
                Text = s.AccountNo.ToString(),
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.AccountList = Accounts;

            return Json(Accounts, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            InPutFM Obj = new InPutFM();
            var Cllst = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Cllst.AddRange("Sp_ClientDrop".ExecuParamsSqlOrStored(false).AsList<ClientDrop>().Select(s => new SelectListItem
            {
                Text = s.FullName,
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.ClientList = Cllst;

            var Accounts = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Accounts.AddRange("Sp_AccountDrop".ExecuParamsSqlOrStored(false, "Id".KVP(0)).AsList<AccountDrop>().Select(s => new SelectListItem
            {
                Text = s.AccountNo.ToString(),
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.AccountList = Accounts;
            var model = "SP_GetAllInPut".ExecuParamsSqlOrStored(false, "TransActionCase".KVP(2)).AsList<InPutVM>().LastOrDefault();
            if (model == null)
            {
                Obj.TransNumber = "01";
            }
            else
            {
                
                int Oldnu = Convert.ToInt32(model.TransNumber);
                int newval = Oldnu + 1;

                Obj.TransNumber =  newval.ToString();
            }

            return View(Obj);
        }
        [HttpPost]
        public ActionResult Create(InPutFM model)
        {

            model.TransDate = DateTime.Now;
            model.ClientDeposit = model.ClientDeposit - 10;

            var data = "SP_AddInput".ExecuParamsSqlOrStored(false, "AccountID".KVP(model.AccountID), "ClientDeposit".KVP(model.ClientDeposit), "Fee".KVP(model.Fee), "Note".KVP(model.Note), "TransDate".KVP(model.TransDate), "TransNumber".KVP(model.TransNumber), "TransActionCase".KVP(2), "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0)
            {


                TempData["success"] = "<script>alert(' تم الاضافه بنجاح');</script>";
                return RedirectToAction("Index1");

            }
            else
                TempData["success"] = "<script>alert(' لم يتم الاضافه ');</script>";

            return RedirectToAction("Index1");

        }


        public ActionResult Edit(int id = 0)
        {
            var Cllst = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Cllst.AddRange("Sp_ClientDrop".ExecuParamsSqlOrStored(false).AsList<ClientDrop>().Select(s => new SelectListItem
            {
                Text = s.FullName,
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.ClientList = Cllst;

            var Accounts = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Accounts.AddRange("Sp_AccountTypeDrop".ExecuParamsSqlOrStored(false).AsList<AccountDrop>().Select(s => new SelectListItem
            {
                Text = s.AccountNo.ToString(),
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.AccountList = Accounts;

            var model = "SP_SelectInputById".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<InPutFM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return View("Create", model.FirstOrDefault());
        }



        [HttpGet]
        public ActionResult Delete(int id, int AccountId, decimal ClientDeposit,int TransActionCase)
        {
            InPutFM obj = new InPutFM();
            obj.Id = id;
            obj.AccountID = AccountId;
            obj.ClientDeposit = ClientDeposit;
            obj.TransActionCase = TransActionCase;
            return PartialView("~/Views/InPut/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id, int AccountId, decimal ClientDeposit,int TransActionCase)
        {
            var data = "SP_DeleteInPut".ExecuParamsSqlOrStored(false, "Id".KVP(Id), "AccountId".KVP(AccountId), "ClientDeposit".KVP(ClientDeposit), "TransActionCase".KVP(TransActionCase)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }

    }
}

Safety/Views/OutPut/Create.cshtml
@model Safety.VM.VM.InPutFM



@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card-box">
    <h4 class="m-t-0 header-title">@ViewBag.Title</h4>
</div>
<div class="card-box">
    @using (Html.BeginForm("Create", "OutPut", FormMethod.Post, new { @style = "margin-bottom: 11px;", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(i => i.Id);

        <div class="form-group row">
            <label class="col-2 col-form-label">رقم العملية</label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.TransNumber, new { @class = "form-control",@Readonly=true, oninvalid = "this.setCustomValidity('من فضلك ادخل هنا')", oninput = "setCustomValidity('')", required = "required" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-2 col-form-label">اسم العميل  </label>

            <div class="col-10">
                @Html.DropDownListFor(x => Model.ClientId, (List<SelectListItem>)ViewBag.ClientList, new
           {
               @class = "form-control select2",
               @onchange = "GetAccount(this.value)"

           })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">نوع الحساب </label>

            <div class="col-10">
                @Html.DropDownListFor(x => Model.AccountID, (List<SelectListItem>)ViewBag.AccountList, new
        {
            @class = "form-control select2"

        })
            </div>
        </div>



        <div class="form-group row">
            <label class="col-2 col-form-label">المبلغ </label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.ClientDeposit, new { @class = "form-control", oninvalid = "this.setCustomValidity('من فضلك ادخل هنا')", oninput = "setCustomValidity('')", required = "required" })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">الرسوم </label>
            <div class="col-10">
<input type="text" readonly value="10" name="Fee" id="Fee"  class="form-control"/> 
            </div>
        </div>
        
        <div class="form-group row">
            <label class="col-2 col-form-label">ملاحظات</label>
            <div class="col-10">
                @Html.TextAreaFor(i => i.Note, new { @class = "form-control", rows = "5" })
            </div>
        </div>

        <div class="col-lg-12" style="text-align: left;">
            <button type="submit" class="btn btn-success btn-rounded w-md waves-effect waves-light m-b-5">حفظ</button>
            <a href="@Url.Action("Index1","OutPut")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5">عودة</a>
        </div>
    }
    <div class="clearfix"></div>
</div>



@section Scripts{

    <script type="text/javascript">
        $(".select2").select2({
            selectOnClose: true   ,
            dir: "rtl",
        });



    </script>
    <script type="text/javascript">

        function GetAccount(ClientId) {
            ClientId = ClientId ? ClientId : 0;

            $.ajax
                ({
                    url: '/Input/GetAccount',
                    type: 'POST',
                    datatype: 'application/json',
                    contentType: 'application/json',
                    data: JSON.stringify({
                        id: ClientId
                    }),
                    success: function (result) {
                       
                        $("#AccountID").html("");
                        $.each((result), function (i, edu) {

                            $("#AccountID").append
                                ($('<option></option>').val(edu.Value).html(edu.Text))
                        })
                    },
                    error: function () {
                        alert("Whooaaa! Something went wrong..")
                    },
                });
        }
    </script>
}

Safety/Views/OutPut/Delete.cshtml
@model Safety.VM.VM.InPutFM

                           
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> حذف  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> هل تريد الحذف ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="حذف" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id,@Model.AccountID,@Model.ClientDeposit,@Model.TransActionCase)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Safety/Views/OutPut/Index1.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Raw(TempData["success"])
<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title">  السحب </h4>

                    <a id="AddNew" href="@Url.Action("Create","OutPut")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" style="float: left;">        اضافة جديد   </a>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {
    <script src="~/AjaxJS/OutPut.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            OutPut.init();

        })

    </script>
}

Safety/Views/OutPut/Search.cshtml
@model IEnumerable<Safety.VM.VM.InPutVM>
@{
    Layout = null;
}

@if (Model != null)
{

    if (User.IsInRole("Admin"))
    {
        <div class="row">
            <div class="col-12">
                <div class="card-box table-responsive">
                    <table class="table table-hover table-bordered datatable" style="width:1000px;" width="100%">
                        <thead style="background-color:#3bafda;color:white;">
                            <tr>
                                <th>رقم العملية</th>
                                <th> اسم العميل </th>
                                <th>رقم الحساب </th>
                                <th>تاريخ العملية  </th>
                                <th>المبلغ  </th>


                                @*<th></th>*@
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.TransNumber</td>
                                    <td>@item.ClientName</td>
                                    <td>@item.AccountName</td>
                                    <td>@item.TransDate</td>
                                    <td>@item.ClientDeposit</td>


                                    @*<td><a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-success   waves-effect waves-light m-b-0"><i class="ti-pencil"></i></a></td>*@

                                    <td>
                                        <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete(@item.Id,@item.AccountID,@item.ClientDeposit,@item.TransActionCase)">  <i class="ti-trash"></i></button>

                                    </td>


                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        }
    }
    <script type="text/javascript">
        $(function () {
            $('.datatable').DataTable();

            //Buttons examples
            var table = $('#datatable-buttons').DataTable({
                lengthChange: false,
                buttons: ['copy', 'excel', 'pdf']
            });

            table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
        });


    </script>