Safety/Controllers/RoleGroupController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Safety.Core;
using Safety.Models;
using Safety.VM.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Safety.Controllers
{
    public class RoleGroupController : Controller
    {
        
        // GET: RoleGroup
        public ActionResult Index1()
        {

            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllRole".ExecuParamsSqlOrStored(false).AsList<RoleVM>();
            return View(model);

        }


        public ActionResult Create()
        {
            RoleVM Obj = new RoleVM();

            return View(Obj);
        }
        [HttpPost]
        public ActionResult Create(RoleVM model)
        {
            ApplicationDbContext cont = new ApplicationDbContext();
            var rolemanger = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(cont));
            var LastId = "SP_GetAllRole".ExecuParamsSqlOrStored(false).AsList<RoleVM>().Count ;
            model.Id =(Convert.ToInt32( LastId) + 1).ToString();

            var role = new IdentityRole();
            role.Name = model.Name;
            rolemanger.Create(role);
                
           


                TempData["success"] = "<script>alert(' تم الاضافه بنجاح');</script>";
                return RedirectToAction("Index1");




        }


        //public ActionResult Edit(int id = 0)
        //{

        //    var model = "SP_SelectRoleById".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<RoleVM>();
        //    if (model == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View("Create", model.FirstOrDefault());
        //}



        [HttpGet]
        public ActionResult Delete(string id)
        {
            RoleVM obj = new RoleVM();
            obj.Id = id;
            return PartialView("~/Views/RoleGroup/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(string Id)
        {
            var data = "SP_DeleteRole".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }


        public ActionResult UserRole()
        {
          

            UserRoleVM model = new UserRoleVM();

            return View(model);
        }

        public ActionResult UserRoleSearch()
        {

            var model = "SP_GetAllUserRole".ExecuParamsSqlOrStored(false).AsList<UserRoleVM>();
            return View(model);
        }



       public ActionResult AddUserRole()
        {
            var UserDrop = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            UserDrop.AddRange("Sp_UserDrop".ExecuParamsSqlOrStored(false).AsList<UserRoleDrop>().Select(s => new SelectListItem
            {
                Text = s.UserName,
                Value = s.Id.ToString(),
                Selected = s.Id == "0" ? true : false
            }).ToList());
            ViewBag.UserLList = UserDrop;
            var RoleDrop = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            RoleDrop.AddRange("Sp_RoleDrop".ExecuParamsSqlOrStored(false).AsList<RoleDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == "0" ? true : false
            }).ToList());
            ViewBag.RoleList = RoleDrop;
            UserRoleVM model = new UserRoleVM();

            return View(model);
        }

        [HttpPost]
        public ActionResult AddUserRole(UserRoleVM model)
        {
            var model1 = "SP_GetAllUserRoleById".ExecuParamsSqlOrStored(false,"UserId".KVP(model.UserId)).AsList<UserRoleVM>();
            if(model1.Count > 0)
            {
                TempData["success"] = "<script>alert(' تم ربط هذا المستخدم بصلاحية من قبل ');</script>";
                return RedirectToAction("UserRole");

            }

            var data = "SP_AddUseRole".ExecuParamsSqlOrStored(false, "UserId".KVP(model.UserId), "RoleId".KVP(model.RoleId)).AsNonQuery();

            if (data != 0)
            {


                TempData["success"] = "<script>alert(' تم الاضافه بنجاح');</script>";
                return RedirectToAction("UserRole");

            }
            else
                TempData["success"] = "<script>alert(' لم يتم الاضافه ');</script>";

            return RedirectToAction("UserRole");
        }



    }
}

Safety/Views/RoleGroup/AddUserRole.cshtml
@model Safety.VM.VM.UserRoleVM



@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card-box">
    <h4 class="m-t-0 header-title">@ViewBag.Title</h4>
</div>
<div class="card-box">
    @using (Html.BeginForm("AddUserRole", "RoleGroup", FormMethod.Post, new { @style = "margin-bottom: 11px;", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {

       

        <div class="form-group row">
            <label class="col-2 col-form-label">اسم المستخدم  </label>

            <div class="col-10">
                @Html.DropDownListFor(x => Model.UserId, (List<SelectListItem>)ViewBag.UserLList, new
                {
                    @class = "form-control select2",

                })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">اسم الصلاحية  </label>

            <div class="col-10">
                @Html.DropDownListFor(x => Model.RoleId, (List<SelectListItem>)ViewBag.RoleList, new
                {
                    @class = "form-control select2"

                })
            </div>
        </div>




        <div class="col-lg-12" style="text-align: left;">
            <button type="submit" class="btn btn-success btn-rounded w-md waves-effect waves-light m-b-5">حفظ</button>
            <a href="@Url.Action("UserRole","RoleGroup")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5">عودة</a>
        </div>
    }
    <div class="clearfix"></div>
</div>



@section Scripts{

    <script type="text/javascript">
        $(".select2").select2({
            selectOnClose: true   ,
            dir: "rtl",
        });



    </script>
  
}

Safety/Views/RoleGroup/Create.cshtml
@model Safety.VM.VM.RoleVM



@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card-box">
    <h4 class="m-t-0 header-title">@ViewBag.Title</h4>
</div>
<div class="card-box">
    @using (Html.BeginForm("Create", "RoleGroup", FormMethod.Post, new { @style = "margin-bottom: 11px;", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {

        <div class="form-group row">
            <label class="col-2 col-form-label">اسم الصلاحية</label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.Name, new { @class = "form-control", required = "required" })
            </div>
        </div>
      
        <div class="col-lg-12" style="text-align: left;">
            <button type="submit" class="btn btn-success btn-rounded w-md waves-effect waves-light m-b-5">حفظ</button>
            <a href="@Url.Action("Index1","RoleGroup")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5">عودة</a>
        </div>
    }
    <div class="clearfix"></div>
</div>

Safety/Views/RoleGroup/Delete.cshtml
@model Safety.VM.VM.RoleVM

                           
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> حذف  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> هل تريد الحذف ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="حذف" class="btn yellow Saveee" onclick="DeleteRow('@Model.Id')" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Safety/Views/RoleGroup/Index1.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Raw(TempData["success"])
<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title"> الصلاحيات </h4>

                    @*<a id="AddNew" href="@Url.Action("Create","RoleGroup")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" style="float: left;">        اضافة جديد   </a>*@
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {
    <script src="~/AjaxJS/RoleGroup.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            RoleGroup.init();

        })

    </script>
}

Safety/Views/RoleGroup/Search.cshtml
@model IEnumerable<Safety.VM.VM.RoleVM>
    @{ 
        Layout = null;
    }

@if (Model != null)
{


<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" style="width:1000px;" width="100%">
                <thead style="background-color:#3bafda;color:white;">
                    <tr>
                        <th>التسلسل</th>
                        <th>اسم الصلاحية</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        


                        @*<td><a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-success   waves-effect waves-light m-b-0"><i class="ti-pencil"></i></a></td>*@

                       

                    </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
}
        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>

Safety/Views/RoleGroup/UserRole.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Raw(TempData["success"])
<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title"> الصلاحيات </h4>

                    <a id="AddNew" href="@Url.Action("AddUserRole","RoleGroup")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" style="float: left;">        اضافة جديد   </a>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {
    <script src="~/AjaxJS/RoleGroupUser.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            RoleGroupUser.init();

        })

    </script>
}

Safety/Views/RoleGroup/UserRoleSearch.cshtml
@model IEnumerable<Safety.VM.VM.UserRoleVM>
    @{ 
        Layout = null;
    }

@if (Model != null)
{


<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" style="width:1000px;" width="100%">
                <thead style="background-color:#3bafda;color:white;">
                    <tr>
                        <th>اسم المستخدم</th>
                        <th>اسم الصلاحية</th>

                      
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.UserId</td>
                        <td>@item.RoleId</td>




                        @*<td><a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-success   waves-effect waves-light m-b-0"><i class="ti-pencil"></i></a></td>*@

                     


                    </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
}
        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>