Safety/Controllers/TransActionController.cs
using Safety.Core;
using Safety.VM.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Safety.Controllers
{
    public class TransActionController : Controller
    {
        [Authorize(Roles = "Admin,User")]

        // GET: TransAction
        public ActionResult Index1()
        {

            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllTransAction".ExecuParamsSqlOrStored(false).AsList<TransActionVM>();
            return View(model);

        }


        [HttpPost]
        public ActionResult GetAccount(int id = 0)
        {

            var Accounts = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Accounts.AddRange("Sp_AccountDrop".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<AccountDrop>().Select(s => new SelectListItem
            {
                Text = s.AccountNo.ToString(),
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.AccountList = Accounts;

            return Json(Accounts, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            TransActionFM Obj = new TransActionFM();
            var Cllst = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Cllst.AddRange("Sp_ClientDrop".ExecuParamsSqlOrStored(false).AsList<ClientDrop>().Select(s => new SelectListItem
            {
                Text = s.FullName,
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.ClientList = Cllst;

            var Accounts = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Accounts.AddRange("Sp_AccountDrop".ExecuParamsSqlOrStored(false, "Id".KVP(0)).AsList<AccountDrop>().Select(s => new SelectListItem
            {
                Text = s.AccountNo.ToString(),
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.AccountList = Accounts;

            return View(Obj);
        }
        [HttpPost]
        public ActionResult Create(TransActionFM model)
        {

            var CurrentAmount = "SP_GetCurrentAmount".ExecuParamsSqlOrStored(false, "AccountID".KVP(model.FromAccountID)).AsList<AccountsFM>().FirstOrDefault();
            if (CurrentAmount.CurrentAmount < model.Amount)
            {
                TempData["success"] = "<script>alert(' الرصيد الحالى اقل من الرصيد المطلوب للتحويل');</script>";
                return RedirectToAction("Index1");
            }

            model.TransDate = DateTime.Now;
            

            var data = "SP_AddTransAction".ExecuParamsSqlOrStored(false, "Amount".KVP(model.Amount), 
                "Fee".KVP(model.Fee), "FromAccountID".KVP(model.FromAccountID), "Note".KVP(model.Note),
                "ToAccountID".KVP(model.ToAccountID), "TransCode".KVP(model.TransCode), "TransDate".KVP(model.TransDate), "Id".KVP(model.ID)).AsNonQuery();
            if (data != 0)
            {


                TempData["success"] = "<script>alert(' تم الاضافه بنجاح');</script>";
                return RedirectToAction("Index1");

            }
            else
                TempData["success"] = "<script>alert(' لم يتم الاضافه ');</script>";

            return RedirectToAction("Index1");

        }


        public ActionResult Edit(int id = 0)
        {
            var Cllst = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Cllst.AddRange("Sp_ClientDrop".ExecuParamsSqlOrStored(false).AsList<ClientDrop>().Select(s => new SelectListItem
            {
                Text = s.FullName,
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.ClientList = Cllst;

            var Accounts = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Accounts.AddRange("Sp_AccountTypeDrop".ExecuParamsSqlOrStored(false).AsList<AccountDrop>().Select(s => new SelectListItem
            {
                Text = s.AccountNo.ToString(),
                Value = s.ID.ToString(),
                Selected = s.ID == 0 ? true : false
            }).ToList());
            ViewBag.AccountList = Accounts;

            var model = "SP_SelectTransActionById".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<TransActionFM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return View("Create", model.FirstOrDefault());
        }



        [HttpGet]
        public ActionResult Delete(int id,int FromAccountID,int ToAccountID, decimal Amount)
        {
            TransActionFM obj = new TransActionFM();
            obj.ID= id;
            obj.FromAccountID = FromAccountID;
            obj.ToAccountID = ToAccountID;
            obj.Amount = Amount;
           
            return PartialView("~/Views/TransAction/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id, int FromAccountID, int ToAccountID, decimal Amount)
        {
            var data = "SP_DeleteTransAction".ExecuParamsSqlOrStored(false, "Id".KVP(Id), "FromAccountID".KVP(FromAccountID), "ToAccountID".KVP(ToAccountID),"Amount".KVP(Amount)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }

    }
}

Safety/Views/TransAction/Create.cshtml
@model Safety.VM.VM.TransActionFM



@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card-box">
    <h4 class="m-t-0 header-title">@ViewBag.Title</h4>
</div>
<div class="card-box">
    @using (Html.BeginForm("Create", "TransAction", FormMethod.Post, new { @style = "margin-bottom: 11px;", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {

        <div class="form-group row">
            <label class="col-2 col-form-label">رقم العملية</label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.TransCode, new { @class = "form-control", oninvalid = "this.setCustomValidity('من فضلك ادخل هنا')", oninput = "setCustomValidity('')", required = "required" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-2 col-form-label">من العميل</label>

            <div class="col-10">
                @Html.DropDownListFor(x => Model.ClientFromID, (List<SelectListItem>)ViewBag.ClientList, new
                {
                    @class = "form-control select2",
                    @onchange = "GetAccount1(this.value)"

                })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">من الحساب </label>

            <div class="col-10">
                @Html.DropDownListFor(x => Model.FromAccountID, (List<SelectListItem>)ViewBag.AccountList, new
                {
                    @class = "form-control select2"

                })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-2 col-form-label">الى العميل</label>

            <div class="col-10">
                @Html.DropDownListFor(x => Model.ClienttoID, (List<SelectListItem>)ViewBag.ClientList, new
                {
                    @class = "form-control select2",
                    @onchange = "GetAccount2(this.value)"

                })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">من الحساب </label>

            <div class="col-10">
                @Html.DropDownListFor(x => Model.ToAccountID, (List<SelectListItem>)ViewBag.AccountList, new
                {
                    @class = "form-control select2"

                })
            </div>
        </div>


        <div class="form-group row">
            <label class="col-2 col-form-label">المبلغ </label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.Amount, new { @class = "form-control", oninvalid = "this.setCustomValidity('من فضلك ادخل هنا')", oninput = "setCustomValidity('')", required = "required" })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">الرسوم </label>
            <div class="col-10">
                <input type="text" readonly value="10" name="Fee" id="Fee" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-2 col-form-label">ملاحظات</label>
            <div class="col-10">
                @Html.TextAreaFor(i => i.Note, new { @class = "form-control", rows = "5" })
            </div>
        </div>

        <div class="col-lg-12" style="text-align: left;">
            <button type="submit" class="btn btn-success btn-rounded w-md waves-effect waves-light m-b-5">حفظ</button>
            <a href="@Url.Action("Index1","Input")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5">عودة</a>
        </div>
    }
    <div class="clearfix"></div>
</div>



@section Scripts{

    <script type="text/javascript">
        $(".select2").select2({
            selectOnClose: true   ,
            dir: "rtl",
        });



    </script>
    <script type="text/javascript">

        function GetAccount1(ClientId) {
            ClientId = ClientId ? ClientId : 0;

            $.ajax
                ({
                    url: '/Input/GetAccount',
                    type: 'POST',
                    datatype: 'application/json',
                    contentType: 'application/json',
                    data: JSON.stringify({
                        id: ClientId
                    }),
                    success: function (result) {
                       
                        $("#FromAccountID").html("");
                        $.each((result), function (i, edu) {

                            $("#FromAccountID").append
                                ($('<option></option>').val(edu.Value).html(edu.Text))
                        })
                    },
                    error: function () {
                        alert("Whooaaa! Something went wrong..")
                    },
                });
        }
        function GetAccount2(ClientId) {
            ClientId = ClientId ? ClientId : 0;

            $.ajax
                ({
                    url: '/Input/GetAccount',
                    type: 'POST',
                    datatype: 'application/json',
                    contentType: 'application/json',
                    data: JSON.stringify({
                        id: ClientId
                    }),
                    success: function (result) {

                        $("#ToAccountID").html("");
                        $.each((result), function (i, edu) {

                            $("#ToAccountID").append
                                ($('<option></option>').val(edu.Value).html(edu.Text))
                        })
                    },
                    error: function () {
                        alert("Whooaaa! Something went wrong..")
                    },
                });
        }
    </script>
}

Safety/Views/TransAction/Delete.cshtml
@model Safety.VM.VM.TransActionFM

                           
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> حذف  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> هل تريد الحذف ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="حذف" class="btn yellow Saveee" onclick="DeleteRow(@Model.ID,@Model.FromAccountID,@Model.ToAccountID,@Model.Amount)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Safety/Views/TransAction/Index1.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Raw(TempData["success"])
<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title">  التحويلات </h4>

                    <a id="AddNew" href="@Url.Action("Create","TransAction")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" style="float: left;">        اضافة جديد   </a>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {
    <script src="~/AjaxJS/TransAction.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            TransAction.init();

        })

    </script>
}

Safety/Views/TransAction/Search.cshtml
@model IEnumerable<Safety.VM.VM.TransActionVM>
@{
    Layout = null;
}

@if (Model != null)
{
    if (User.IsInRole("Admin"))
    {

        <div class="row">
            <div class="col-12">
                <div class="card-box table-responsive">
                    <table class="table table-hover table-bordered datatable" style="width:1000px;" width="100%">
                        <thead style="background-color:#3bafda;color:white;">
                            <tr>
                                <th>رقم العملية</th>
                                <th>  من </th>
                                <th>رقم الحساب </th>
                                <th>الى  </th>
                                <th>رقم الحساب </th>
                                <th>تاريخ العملية  </th>
                                <th>المبلغ  </th>


                                @*<th></th>*@
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.TransCode</td>
                                    <td>@item.ClientFromName</td>
                                    <td>@item.FromAccountName</td>
                                    <td>@item.ClienttoName</td>
                                    <td>@item.ToAccountName</td>
                                    <td>@item.TransDate</td>
                                    <td>@item.Amount</td>


                                    @*<td><a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-success   waves-effect waves-light m-b-0"><i class="ti-pencil"></i></a></td>*@

                                    <td>
                                        <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete('@item.ID','@item.FromAccountName','@item.ToAccountName','@item.Amount')">  <i class="ti-trash"></i></button>

                                    </td>


                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        }
    }
    <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


    </script>