Safety/Controllers/ClientController.cs
using Safety.Core;
using Safety.VM.VM;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Safety.Controllers
{
    [Authorize(Roles = "Admin,Client")]

    public class ClientController : Controller
    {
        // GET: Client
        public ActionResult Index1()
        {

            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllClient".ExecuParamsSqlOrStored(false).AsList<ClientVM>();
            return View(model);

        }


        public ActionResult Create()
        {
            ClientVM Obj = new ClientVM();

            return View(Obj);
        }
        [HttpPost]
        public ActionResult Create(ClientVM model)
        {
            model.StartDate = DateTime.Now;
            if (Request.Files.Count > 0)
            {


              
                if ( Request.Files != null)
                {
                   
                    var file = Request.Files[0];
                    
                    var fileNameWithExtension = Path.GetFileName(file.FileName);
                    var fileNameOnly = Path.GetFileNameWithoutExtension(file.FileName);
                    string RootPath = Server.MapPath("~/Images/");
                    if (!Directory.Exists(RootPath))
                    {
                        Directory.CreateDirectory(RootPath);
                    }
                    var unique = new Guid();
                    var path = Path.Combine(RootPath, fileNameOnly + unique + Path.GetExtension(file.FileName));
                    file.SaveAs(path);
                    model.IDPhoto1 = "Images/" + fileNameOnly + unique + Path.GetExtension(file.FileName);

                    var file2 = Request.Files[1];
                  
                    var fileNameWithExtension2 = Path.GetFileName(file2.FileName);
                    var fileNameOnly2 = Path.GetFileNameWithoutExtension(file2.FileName);
                    string RootPath2= Server.MapPath("~/Images/");
                    if (!Directory.Exists(RootPath))
                    {
                        Directory.CreateDirectory(RootPath);
                    }
                    var unique2 = new Guid();
                    var path2 = Path.Combine(RootPath2, fileNameOnly2 + unique2 + Path.GetExtension(file2.FileName));
                    file2.SaveAs(path2);
                    model.IDPhoto2 = "Images/" + fileNameOnly2 + unique2 + Path.GetExtension(file2.FileName);


                }




            }

            var data = "SP_AddClient".ExecuParamsSqlOrStored(false, "Address".KVP(model.Address), "Email".KVP(model.Email), "FullName".KVP(model.FullName)
                , "IDPhoto1".KVP(model.IDPhoto1), "IDPhoto2".KVP(model.IDPhoto2), "IsActive".KVP(model.IsActive), "Mobile".KVP(model.Mobile), "Note".KVP(model.Note), "StartDate".KVP(model.StartDate), "Id".KVP(model.ID)).AsNonQuery();
            if (data != 0)
            {


                TempData["success"] = "<script>alert(' تم الاضافه بنجاح');</script>";
                return RedirectToAction("Index1");

            }
            else
                TempData["success"] = "<script>alert(' لم يتم الاضافه ');</script>";

            return RedirectToAction("Index1");

        }


        public ActionResult Edit(int id = 0)
        {

            var model = "SP_SelectClient".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<ClientVM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return View("Create", model.FirstOrDefault());
        }



        [HttpGet]
        public ActionResult Delete(int id)
        {
            ClientVM obj = new ClientVM();
            obj.ID = id;
            return PartialView("~/Views/Client/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeleteClient".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }

    }
}

Safety/Views/Client/Create.cshtml
@model Safety.VM.VM.ClientVM



@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card-box">
    <h4 class="m-t-0 header-title">@ViewBag.Title</h4>
</div>
<div class="card-box">
    @using (Html.BeginForm("Create", "Client", FormMethod.Post, new { @style = "margin-bottom: 11px;", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(i => i.ID);

        @Html.HiddenFor(i => i.ID)
        @Html.HiddenFor(i => i.IDPhoto1)
        @Html.HiddenFor(i => i.IDPhoto2)

       
        <div class="form-group row">
            <label class="col-2 col-form-label">اسم العميل</label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.FullName, new { @class = "form-control", required = "required" })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">العنوان</label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.Address, new { @class = "form-control", required = "required" })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">الموبايل</label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.Mobile, new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(i => i.Mobile)
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">البريد الاليكتروني</label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.Email, new { @class = "form-control", @type = "email" })
                @Html.ValidationMessageFor(i => i.Email)
            </div>
        </div>
        @*<div class="form-group row">
            <label class="col-2 col-form-label">تاريخ الاشتراك</label>
            <div class="col-10">
                <div class=" input-group">
                    <input type="text" name="StartDate" required id="StartDate" class="form-control" value="@Model.StartDate" />

                </div>
            </div>
        </div>*@
        <div class="form-group row">
            <label class="col-2 col-form-label">نشط</label>
            <div class="col-10">
                @Html.CheckBoxFor(i => i.IsActive, new { data_plugin = "switchery", data_color = "#3bafda", data_switchery = "true" })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-2 col-form-label">ملاحظات</label>
            <div class="col-10">
                @Html.TextAreaFor(i => i.Note, new { @class = "form-control", rows = "5" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-2 col-form-label">صورة البطاقة 1</label>
            <div class="col-10">
                @Html.TextBoxFor(m => m.IDPhoto1, new { type = "file" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-2 col-form-label">صورة البطاقة 2</label>
            <div class="col-10">
                @Html.TextBoxFor(m => m.IDPhoto2, new { type = "file" })
            </div>
        </div>

        <div class="col-lg-12" style="text-align: left;">
            <button type="submit" class="btn btn-success btn-rounded w-md waves-effect waves-light m-b-5">حفظ</button>
            <a href="@Url.Action("Index1","Client")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5">عودة</a>
        </div>
    }
    <div class="clearfix"></div>
</div>


<script>
            $(function () {
                $("#StartDate").datepicker().datepicker("setDate", new Date());

            });
</script>

Safety/Views/Client/Delete.cshtml
@model Safety.VM.VM.ClientVM

                           
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> حذف  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> هل تريد الحذف ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="حذف" class="btn yellow Saveee" onclick="DeleteRow(@Model.ID)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Safety/Views/Client/Index1.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Raw(TempData["success"])
<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title"> العملاء </h4>

                    <a id="AddNew" href="@Url.Action("Create","Client")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" style="float: left;">        اضافة جديد   </a>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {
    <script src="~/AjaxJS/Client.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            Client.init();

        })

    </script>
}

Safety/Views/Client/Search.cshtml
@model IEnumerable<Safety.VM.VM.ClientVM>
    @{ 
        Layout = null;
    }

@if (Model != null)
{


<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" style="width:1000px;" width="100%">
                <thead style="background-color:#3bafda;color:white;">
                    <tr>
                        <th>التسلسل</th>
                        <th>اسم العميل</th>
                        <th>عنوان العميل </th>
                        <th> رقم العميل </th>
                        <th>البريد الالكترونى  </th>
                        @if (User.IsInRole("Admin"))
                        {
                    <th></th>
                    <th></th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.ID</td>
                        <td>@item.FullName</td>
                        <td>@item.Address</td>
                        <td>@item.Mobile</td>
                        <td>@item.Email</td>
                        @if (User.IsInRole("Admin"))
                        {

                        <td><a href="@Url.Action("Edit", new { id = item.ID })" class="btn btn-success   waves-effect waves-light m-b-0"><i class="ti-pencil"></i></a></td>

                        <td>
                            <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete(@item.ID)">  <i class="ti-trash"></i></button>

                        </td>
                        }

                    </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
}
        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>